import { ListV2Index } from './src/main/ets/pages/list/ListV2Index';
import { GridV2Index } from './src/main/ets/pages/grid/GridV2Index';
import { FlowV2Index } from './src/main/ets/pages/flow/FlowV2Index';
import { Rv2WebViewPage } from './src/main/ets/pages/rv/v2/Rv2WebViewPage';
import { Rv2WaterFlowUpAndDownPage } from './src/main/ets/pages/rv/v2/Rv2WaterFlowUpAndDownPage';
import { Rv2RefreshUpAndDownPage } from './src/main/ets/pages/rv/v2/Rv2RefreshUpAndDownPage';
import { Rv2RefreshScrollPage } from './src/main/ets/pages/rv/v2/Rv2RefreshScrollPage';
import { Rv2RefreshPointPage } from './src/main/ets/pages/rv/v2/Rv2RefreshPointPage';
import { Rv2RefreshImmersivePage } from './src/main/ets/pages/rv/v2/Rv2RefreshImmersivePage';
import { Rv2RefreshHeaderAndFooterPage } from './src/main/ets/pages/rv/v2/Rv2RefreshHeaderAndFooterPage';
import { Rv2NoScrollSpringPage } from './src/main/ets/pages/rv/v2/Rv2NoScrollSpringPage';
import { Rv2MultiViewPage } from './src/main/ets/pages/rv/v2/Rv2MultiViewPage';
import { Rv2MaxScrollSpringPage } from './src/main/ets/pages/rv/v2/Rv2MaxScrollSpringPage';
import { Rv2LoadDataSpringBackPage } from './src/main/ets/pages/rv/v2/Rv2LoadDataSpringBackPage';
import { Rv2ListUpAndDownPage } from './src/main/ets/pages/rv/v2/Rv2ListUpAndDownPage';
import { Rv2LazyDataOperationPage } from './src/main/ets/pages/rv/v2/Rv2LazyDataOperationPage';
import { Rv2Index } from './src/main/ets/pages/rv/v2/Rv2Index';
import { Rv2GridUpAndDownPage } from './src/main/ets/pages/rv/v2/Rv2GridUpAndDownPage';
import { Rv2FooterNothingPage } from './src/main/ets/pages/rv/v2/Rv2FooterNothingPage';
import { Rv2FixedFooterPage } from './src/main/ets/pages/rv/v2/Rv2FixedFooterPage';
import { Rv2AutoRefreshPage } from './src/main/ets/pages/rv/v2/Rv2AutoRefreshPage';
import { Rv2AutoListUpAndDownPage } from './src/main/ets/pages/rv/v2/Rv2AutoListUpAndDownPage';
import { Rv2AdaptiveHeightPage } from './src/main/ets/pages/rv/v2/Rv2AdaptiveHeightPage';
import { LitheV2WebViewPage } from './src/main/ets/pages/lithe/v2/LitheV2WebViewPage';
import { LitheV2WaterFlowUpAndDownPage } from './src/main/ets/pages/lithe/v2/LitheV2WaterFlowUpAndDownPage';
import { LitheV2RefreshUpAndDownPage } from './src/main/ets/pages/lithe/v2/LitheV2RefreshUpAndDownPage';
import { LitheV2RefreshScrollPage } from './src/main/ets/pages/lithe/v2/LitheV2RefreshScrollPage';
import { LitheV2RefreshPointPage } from './src/main/ets/pages/lithe/v2/LitheV2RefreshPointPage';
import { LitheV2RefreshImmersivePage } from './src/main/ets/pages/lithe/v2/LitheV2RefreshImmersivePage';
import { LitheV2RefreshHeaderAndFooterPage } from './src/main/ets/pages/lithe/v2/LitheV2RefreshHeaderAndFooterPage';
import { LitheV2NoScrollSpringPage } from './src/main/ets/pages/lithe/v2/LitheV2NoScrollSpringPage';
import { LitheV2MultiViewPage } from './src/main/ets/pages/lithe/v2/LitheV2MultiViewPage';
import { LitheV2LoadDataSpringBackPage } from './src/main/ets/pages/lithe/v2/LitheV2LoadDataSpringBackPage';
import { LitheV2ListUpAndDownPage } from './src/main/ets/pages/lithe/v2/LitheV2ListUpAndDownPage';
import { LitheV2ListMaxSpringPage } from './src/main/ets/pages/lithe/v2/LitheV2ListMaxSpringPage';
import { LitheV2LazyDataOperationPage } from './src/main/ets/pages/lithe/v2/LitheV2LazyDataOperationPage';
import { LitheV2LayoutHeaderPage } from './src/main/ets/pages/lithe/v2/LitheV2LayoutHeaderPage';
import { LitheV2Index } from './src/main/ets/pages/lithe/v2/LitheV2Index';
import { LitheV2GridUpAndDownPage } from './src/main/ets/pages/lithe/v2/LitheV2GridUpAndDownPage';
import { LitheV2FooterNothingPage } from './src/main/ets/pages/lithe/v2/LitheV2FooterNothingPage';
import { LitheV2FixedFooterPage } from './src/main/ets/pages/lithe/v2/LitheV2FixedFooterPage';
import { LitheV2AutoRefreshPage } from './src/main/ets/pages/lithe/v2/LitheV2AutoRefreshPage';
import { LitheV2AutoListUpAndDownPage } from './src/main/ets/pages/lithe/v2/LitheV2AutoListUpAndDownPage';
import { LitheV2AdaptiveHeightPage } from './src/main/ets/pages/lithe/v2/LitheV2AdaptiveHeightPage';
import { ListViewV2UpAndDownPage } from './src/main/ets/pages/list/v2/view/ListViewV2UpAndDownPage';
import { ListViewV2UpAndDownLazyPage } from './src/main/ets/pages/list/v2/view/ListViewV2UpAndDownLazyPage';
import { ListViewV2TabsPage } from './src/main/ets/pages/list/v2/view/ListViewV2TabsPage';
import { ListViewV2SwipeActionPage } from './src/main/ets/pages/list/v2/view/ListViewV2SwipeActionPage';
import { ListViewV2StickyTopPage } from './src/main/ets/pages/list/v2/view/ListViewV2StickyTopPage';
import { ListViewV2StickyRLTopPage } from './src/main/ets/pages/list/v2/view/ListViewV2StickyRLTopPage';
import { ListViewV2StickLayoutPage } from './src/main/ets/pages/list/v2/view/ListViewV2StickLayoutPage';
import { ListViewV2SpringRatioPage } from './src/main/ets/pages/list/v2/view/ListViewV2SpringRatioPage';
import { ListViewV2SlideDeletePage } from './src/main/ets/pages/list/v2/view/ListViewV2SlideDeletePage';
import { ListViewV2RefreshPage } from './src/main/ets/pages/list/v2/view/ListViewV2RefreshPage';
import { ListViewV2RefreshHeaderFooterPage } from './src/main/ets/pages/list/v2/view/ListViewV2RefreshHeaderFooterPage';
import { ListViewV2PositioningPage } from './src/main/ets/pages/list/v2/view/ListViewV2PositioningPage';
import { ListViewV2Page } from './src/main/ets/pages/list/v2/view/ListViewV2Page';
import { ListViewV2NoSpringPage } from './src/main/ets/pages/list/v2/view/ListViewV2NoSpringPage';
import { ListViewV2NoReboundPage } from './src/main/ets/pages/list/v2/view/ListViewV2NoReboundPage';
import { ListViewV2NoDataPage } from './src/main/ets/pages/list/v2/view/ListViewV2NoDataPage';
import { ListViewV2MaxSpringPage } from './src/main/ets/pages/list/v2/view/ListViewV2MaxSpringPage';
import { ListViewV2LoadMorePage } from './src/main/ets/pages/list/v2/view/ListViewV2LoadMorePage';
import { ListViewV2LazyPage } from './src/main/ets/pages/list/v2/view/ListViewV2LazyPage';
import { ListViewV2LazyDataOperationPage } from './src/main/ets/pages/list/v2/view/ListViewV2LazyDataOperationPage';
import { ListViewV2ItemGroupPage } from './src/main/ets/pages/list/v2/view/ListViewV2ItemGroupPage';
import { ListViewV2ItemGroupNoStickyPage } from './src/main/ets/pages/list/v2/view/ListViewV2ItemGroupNoStickyPage';
import { ListViewV2ItemGroupIndexPage } from './src/main/ets/pages/list/v2/view/ListViewV2ItemGroupIndexPage';
import { ListViewV2HeaderPage } from './src/main/ets/pages/list/v2/view/ListViewV2HeaderPage';
import { ListViewV2HeaderAndFooterPage } from './src/main/ets/pages/list/v2/view/ListViewV2HeaderAndFooterPage';
import { ListViewV2FooterPage } from './src/main/ets/pages/list/v2/view/ListViewV2FooterPage';
import { ListViewV2FixedBottomLoadPage } from './src/main/ets/pages/list/v2/view/ListViewV2FixedBottomLoadPage';
import { ListViewV2ErrorOrEmptyPage } from './src/main/ets/pages/list/v2/view/ListViewV2ErrorOrEmptyPage';
import { ListViewV2EnableSpringPage } from './src/main/ets/pages/list/v2/view/ListViewV2EnableSpringPage';
import { ListViewV2DataOperationPage } from './src/main/ets/pages/list/v2/view/ListViewV2DataOperationPage';
import { ListViewV2AutoRefreshPage } from './src/main/ets/pages/list/v2/view/ListViewV2AutoRefreshPage';
import { ListViewV2AutoLoadMorePage } from './src/main/ets/pages/list/v2/view/ListViewV2AutoLoadMorePage';
import { ListViewV2ArbitrarilyStickyTopPage } from './src/main/ets/pages/list/v2/view/ListViewV2ArbitrarilyStickyTopPage';
import { ListViewV2AdaptivePage2 } from './src/main/ets/pages/list/v2/view/ListViewV2AdaptivePage2';
import { ListViewV2AdaptivePage } from './src/main/ets/pages/list/v2/view/ListViewV2AdaptivePage';
import { ListLayoutV2UpAndDownPage } from './src/main/ets/pages/list/v2/layout/ListLayoutV2UpAndDownPage';
import { ListLayoutV2TabsPage } from './src/main/ets/pages/list/v2/layout/ListLayoutV2TabsPage';
import { ListLayoutV2SwipeActionPage } from './src/main/ets/pages/list/v2/layout/ListLayoutV2SwipeActionPage';
import { ListLayoutV2StickyTopRefreshPage } from './src/main/ets/pages/list/v2/layout/ListLayoutV2StickyTopRefreshPage';
import { ListLayoutV2StickyTopPage } from './src/main/ets/pages/list/v2/layout/ListLayoutV2StickyTopPage';
import { ListLayoutV2StickPage } from './src/main/ets/pages/list/v2/layout/ListLayoutV2StickPage';
import { ListLayoutV2SpringRatioPage } from './src/main/ets/pages/list/v2/layout/ListLayoutV2SpringRatioPage';
import { ListLayoutV2SlideDeletePage } from './src/main/ets/pages/list/v2/layout/ListLayoutV2SlideDeletePage';
import { ListLayoutV2RefreshPage } from './src/main/ets/pages/list/v2/layout/ListLayoutV2RefreshPage';
import { ListLayoutV2RefreshHeaderFooterPage } from './src/main/ets/pages/list/v2/layout/ListLayoutV2RefreshHeaderFooterPage';
import { ListLayoutV2PositioningPage } from './src/main/ets/pages/list/v2/layout/ListLayoutV2PositioningPage';
import { ListLayoutV2Page } from './src/main/ets/pages/list/v2/layout/ListLayoutV2Page';
import { ListLayoutV2NoSpringPage } from './src/main/ets/pages/list/v2/layout/ListLayoutV2NoSpringPage';
import { ListLayoutV2NoReboundPage } from './src/main/ets/pages/list/v2/layout/ListLayoutV2NoReboundPage';
import { ListLayoutV2MaxSpringPage } from './src/main/ets/pages/list/v2/layout/ListLayoutV2MaxSpringPage';
import { ListLayoutV2LoadMorePage } from './src/main/ets/pages/list/v2/layout/ListLayoutV2LoadMorePage';
import { ListLayoutV2LazyUpAndDownPage } from './src/main/ets/pages/list/v2/layout/ListLayoutV2LazyUpAndDownPage';
import { ListLayoutV2LazyPage } from './src/main/ets/pages/list/v2/layout/ListLayoutV2LazyPage';
import { ListLayoutV2LazyDataOperationPage } from './src/main/ets/pages/list/v2/layout/ListLayoutV2LazyDataOperationPage';
import { ListLayoutV2ItemGroupPage } from './src/main/ets/pages/list/v2/layout/ListLayoutV2ItemGroupPage';
import { ListLayoutV2ItemGroupNoStickyPage } from './src/main/ets/pages/list/v2/layout/ListLayoutV2ItemGroupNoStickyPage';
import { ListLayoutV2ItemGroupIndexPage } from './src/main/ets/pages/list/v2/layout/ListLayoutV2ItemGroupIndexPage';
import { ListLayoutV2HeaderPage } from './src/main/ets/pages/list/v2/layout/ListLayoutV2HeaderPage';
import { ListLayoutV2HeaderAndFooterPage } from './src/main/ets/pages/list/v2/layout/ListLayoutV2HeaderAndFooterPage';
import { ListLayoutV2FooterPage } from './src/main/ets/pages/list/v2/layout/ListLayoutV2FooterPage';
import { ListLayoutV2FixedFooterPage } from './src/main/ets/pages/list/v2/layout/ListLayoutV2FixedFooterPage';
import { ListLayoutV2FixedBottomLoadPage } from './src/main/ets/pages/list/v2/layout/ListLayoutV2FixedBottomLoadPage';
import { ListLayoutV2ErrorOrEmptyPage } from './src/main/ets/pages/list/v2/layout/ListLayoutV2ErrorOrEmptyPage';
import { ListLayoutV2EnableSpringPage } from './src/main/ets/pages/list/v2/layout/ListLayoutV2EnableSpringPage';
import { ListLayoutV2DataOperationPage } from './src/main/ets/pages/list/v2/layout/ListLayoutV2DataOperationPage';
import { ListLayoutV2AutoRefreshPage } from './src/main/ets/pages/list/v2/layout/ListLayoutV2AutoRefreshPage';
import { ListLayoutV2AutoLoadMorePage } from './src/main/ets/pages/list/v2/layout/ListLayoutV2AutoLoadMorePage';
import { ListLayoutV2ArbitrarilyStickyTopPage } from './src/main/ets/pages/list/v2/layout/ListLayoutV2ArbitrarilyStickyTopPage';
import { ListLayoutV2AdaptivePage2 } from './src/main/ets/pages/list/v2/layout/ListLayoutV2AdaptivePage2';
import { ListLayoutV2AdaptivePage } from './src/main/ets/pages/list/v2/layout/ListLayoutV2AdaptivePage';
import { GridViewV2TabsPage } from './src/main/ets/pages/grid/v2/view/GridViewV2TabsPage';
import { GridViewV2StickyTopPage } from './src/main/ets/pages/grid/v2/view/GridViewV2StickyTopPage';
import { GridViewV2StickyRLTopPage } from './src/main/ets/pages/grid/v2/view/GridViewV2StickyRLTopPage';
import { GridViewV2StickLayoutViewPage } from './src/main/ets/pages/grid/v2/view/GridViewV2StickLayoutViewPage';
import { GridViewV2SpringRatioPage } from './src/main/ets/pages/grid/v2/view/GridViewV2SpringRatioPage';
import { GridViewV2RefreshPage } from './src/main/ets/pages/grid/v2/view/GridViewV2RefreshPage';
import { GridViewV2RefreshHeaderFooterPage } from './src/main/ets/pages/grid/v2/view/GridViewV2RefreshHeaderFooterPage';
import { GridViewV2RefreshAndLoadPage } from './src/main/ets/pages/grid/v2/view/GridViewV2RefreshAndLoadPage';
import { GridViewV2PositioningPage } from './src/main/ets/pages/grid/v2/view/GridViewV2PositioningPage';
import { GridViewV2Page } from './src/main/ets/pages/grid/v2/view/GridViewV2Page';
import { GridViewV2NoSpringPage } from './src/main/ets/pages/grid/v2/view/GridViewV2NoSpringPage';
import { GridViewV2NoReboundPage } from './src/main/ets/pages/grid/v2/view/GridViewV2NoReboundPage';
import { GridViewV2NoDataPage } from './src/main/ets/pages/grid/v2/view/GridViewV2NoDataPage';
import { GridViewV2MaxSpringPage } from './src/main/ets/pages/grid/v2/view/GridViewV2MaxSpringPage';
import { GridViewV2LoadMorePage } from './src/main/ets/pages/grid/v2/view/GridViewV2LoadMorePage';
import { GridViewV2LazyRefreshAndLoadPage } from './src/main/ets/pages/grid/v2/view/GridViewV2LazyRefreshAndLoadPage';
import { GridViewV2LazyPage } from './src/main/ets/pages/grid/v2/view/GridViewV2LazyPage';
import { GridViewV2HeaderPage } from './src/main/ets/pages/grid/v2/view/GridViewV2HeaderPage';
import { GridViewV2HeaderAndFooterPage } from './src/main/ets/pages/grid/v2/view/GridViewV2HeaderAndFooterPage';
import { GridViewV2FooterPage } from './src/main/ets/pages/grid/v2/view/GridViewV2FooterPage';
import { GridViewV2FixedBottomLoadPage } from './src/main/ets/pages/grid/v2/view/GridViewV2FixedBottomLoadPage';
import { GridViewV2EnableSpringPage } from './src/main/ets/pages/grid/v2/view/GridViewV2EnableSpringPage';
import { GridViewV2AutoRefreshPage } from './src/main/ets/pages/grid/v2/view/GridViewV2AutoRefreshPage';
import { GridViewV2AutoLoadMorePage } from './src/main/ets/pages/grid/v2/view/GridViewV2AutoLoadMorePage';
import { GridViewV2ArbitrarilyStickyTopPage } from './src/main/ets/pages/grid/v2/view/GridViewV2ArbitrarilyStickyTopPage';
import { GridViewV2AdaptiveTopPage } from './src/main/ets/pages/grid/v2/view/GridViewV2AdaptiveTopPage';
import { GridViewV2AdaptiveBottomPage } from './src/main/ets/pages/grid/v2/view/GridViewV2AdaptiveBottomPage';
import { GridV2DropPage } from './src/main/ets/pages/grid/v2/view/GridV2DropPage';
import { GridLayoutV2TabsPage } from './src/main/ets/pages/grid/v2/layout/GridLayoutV2TabsPage';
import { GridLayoutV2StickyTopPage } from './src/main/ets/pages/grid/v2/layout/GridLayoutV2StickyTopPage';
import { GridLayoutV2StickyRLTopPage } from './src/main/ets/pages/grid/v2/layout/GridLayoutV2StickyRLTopPage';
import { GridLayoutV2StickLayoutViewPage } from './src/main/ets/pages/grid/v2/layout/GridLayoutV2StickLayoutViewPage';
import { GridLayoutV2SpringRatioPage } from './src/main/ets/pages/grid/v2/layout/GridLayoutV2SpringRatioPage';
import { GridLayoutV2RefreshPage } from './src/main/ets/pages/grid/v2/layout/GridLayoutV2RefreshPage';
import { GridLayoutV2RefreshHeaderFooterPage } from './src/main/ets/pages/grid/v2/layout/GridLayoutV2RefreshHeaderFooterPage';
import { GridLayoutV2RefreshAndLoadPage } from './src/main/ets/pages/grid/v2/layout/GridLayoutV2RefreshAndLoadPage';
import { GridLayoutV2PositioningPage } from './src/main/ets/pages/grid/v2/layout/GridLayoutV2PositioningPage';
import { GridLayoutV2Page } from './src/main/ets/pages/grid/v2/layout/GridLayoutV2Page';
import { GridLayoutV2NoSpringPage } from './src/main/ets/pages/grid/v2/layout/GridLayoutV2NoSpringPage';
import { GridLayoutV2NoReboundPage } from './src/main/ets/pages/grid/v2/layout/GridLayoutV2NoReboundPage';
import { GridLayoutV2NoDataPage } from './src/main/ets/pages/grid/v2/layout/GridLayoutV2NoDataPage';
import { GridLayoutV2MaxSpringPage } from './src/main/ets/pages/grid/v2/layout/GridLayoutV2MaxSpringPage';
import { GridLayoutV2LoadMorePage } from './src/main/ets/pages/grid/v2/layout/GridLayoutV2LoadMorePage';
import { GridLayoutV2LazyRefreshAndLoadPage } from './src/main/ets/pages/grid/v2/layout/GridLayoutV2LazyRefreshAndLoadPage';
import { GridLayoutV2LazyPage } from './src/main/ets/pages/grid/v2/layout/GridLayoutV2LazyPage';
import { GridLayoutV2HeaderPage } from './src/main/ets/pages/grid/v2/layout/GridLayoutV2HeaderPage';
import { GridLayoutV2HeaderAndFooterPage } from './src/main/ets/pages/grid/v2/layout/GridLayoutV2HeaderAndFooterPage';
import { GridLayoutV2FooterPage } from './src/main/ets/pages/grid/v2/layout/GridLayoutV2FooterPage';
import { GridLayoutV2FixedBottomLoadPage } from './src/main/ets/pages/grid/v2/layout/GridLayoutV2FixedBottomLoadPage';
import { GridLayoutV2EnableSpringPage } from './src/main/ets/pages/grid/v2/layout/GridLayoutV2EnableSpringPage';
import { GridLayoutV2AutoRefreshPage } from './src/main/ets/pages/grid/v2/layout/GridLayoutV2AutoRefreshPage';
import { GridLayoutV2AutoLoadMorePage } from './src/main/ets/pages/grid/v2/layout/GridLayoutV2AutoLoadMorePage';
import { GridLayoutV2ArbitrarilyStickyTopPage } from './src/main/ets/pages/grid/v2/layout/GridLayoutV2ArbitrarilyStickyTopPage';
import { GridLayoutV2AdaptiveTopPage } from './src/main/ets/pages/grid/v2/layout/GridLayoutV2AdaptiveTopPage';
import { GridLayoutV2AdaptiveBottomPage } from './src/main/ets/pages/grid/v2/layout/GridLayoutV2AdaptiveBottomPage';
import { FlowViewV2TopActionBarPage } from './src/main/ets/pages/flow/v2/view/FlowViewV2TopActionBarPage';
import { FlowViewV2TabsPage } from './src/main/ets/pages/flow/v2/view/FlowViewV2TabsPage';
import { FlowViewV2StickyTopPage } from './src/main/ets/pages/flow/v2/view/FlowViewV2StickyTopPage';
import { FlowViewV2StickyTopActionBarPage } from './src/main/ets/pages/flow/v2/view/FlowViewV2StickyTopActionBarPage';
import { FlowViewV2StickyRLTopPage } from './src/main/ets/pages/flow/v2/view/FlowViewV2StickyRLTopPage';
import { FlowViewV2SpringRatioPage } from './src/main/ets/pages/flow/v2/view/FlowViewV2SpringRatioPage';
import { FlowViewV2RefreshPage } from './src/main/ets/pages/flow/v2/view/FlowViewV2RefreshPage';
import { FlowViewV2RefreshHeaderAndFooterPage } from './src/main/ets/pages/flow/v2/view/FlowViewV2RefreshHeaderAndFooterPage';
import { FlowViewV2RefreshAndLoadMorePage } from './src/main/ets/pages/flow/v2/view/FlowViewV2RefreshAndLoadMorePage';
import { FlowViewV2PositioningPage } from './src/main/ets/pages/flow/v2/view/FlowViewV2PositioningPage';
import { FlowViewV2Page } from './src/main/ets/pages/flow/v2/view/FlowViewV2Page';
import { FlowViewV2NoSpringPage } from './src/main/ets/pages/flow/v2/view/FlowViewV2NoSpringPage';
import { FlowViewV2NoReboundPage } from './src/main/ets/pages/flow/v2/view/FlowViewV2NoReboundPage';
import { FlowViewV2NoDataPage } from './src/main/ets/pages/flow/v2/view/FlowViewV2NoDataPage';
import { FlowViewV2MaxSpringPage } from './src/main/ets/pages/flow/v2/view/FlowViewV2MaxSpringPage';
import { FlowViewV2LoadMorePage } from './src/main/ets/pages/flow/v2/view/FlowViewV2LoadMorePage';
import { FlowViewV2LazyRefreshAndLoadMorePage } from './src/main/ets/pages/flow/v2/view/FlowViewV2LazyRefreshAndLoadMorePage';
import { FlowViewV2LazyPage } from './src/main/ets/pages/flow/v2/view/FlowViewV2LazyPage';
import { FlowViewV2HeaderPage } from './src/main/ets/pages/flow/v2/view/FlowViewV2HeaderPage';
import { FlowViewV2HeaderAndFooterPage } from './src/main/ets/pages/flow/v2/view/FlowViewV2HeaderAndFooterPage';
import { FlowViewV2FooterPage } from './src/main/ets/pages/flow/v2/view/FlowViewV2FooterPage';
import { FlowViewV2FixedBottomPage } from './src/main/ets/pages/flow/v2/view/FlowViewV2FixedBottomPage';
import { FlowViewV2EnableSpringPage } from './src/main/ets/pages/flow/v2/view/FlowViewV2EnableSpringPage';
import { FlowViewV2AutoRefreshPage } from './src/main/ets/pages/flow/v2/view/FlowViewV2AutoRefreshPage';
import { FlowViewV2AutoLoadMorePage } from './src/main/ets/pages/flow/v2/view/FlowViewV2AutoLoadMorePage';
import { FlowViewV2ArbitrarilyStickyTopPage } from './src/main/ets/pages/flow/v2/view/FlowViewV2ArbitrarilyStickyTopPage';
import { FlowViewV2AdaptiveTopPage } from './src/main/ets/pages/flow/v2/view/FlowViewV2AdaptiveTopPage';
import { FlowViewV2AdaptiveBottomPage } from './src/main/ets/pages/flow/v2/view/FlowViewV2AdaptiveBottomPage';
import { FlowLayoutV2TopActionBarPage } from './src/main/ets/pages/flow/v2/layout/FlowLayoutV2TopActionBarPage';
import { FlowLayoutV2TabsPage } from './src/main/ets/pages/flow/v2/layout/FlowLayoutV2TabsPage';
import { FlowLayoutV2StickyTopPage } from './src/main/ets/pages/flow/v2/layout/FlowLayoutV2StickyTopPage';
import { FlowLayoutV2StickyRLTopPage } from './src/main/ets/pages/flow/v2/layout/FlowLayoutV2StickyRLTopPage';
import { FlowLayoutV2SpringRatioPage } from './src/main/ets/pages/flow/v2/layout/FlowLayoutV2SpringRatioPage';
import { FlowLayoutV2RefreshPage } from './src/main/ets/pages/flow/v2/layout/FlowLayoutV2RefreshPage';
import { FlowLayoutV2RefreshHeaderAndFooterPage } from './src/main/ets/pages/flow/v2/layout/FlowLayoutV2RefreshHeaderAndFooterPage';
import { FlowLayoutV2RefreshAndLoadMorePage } from './src/main/ets/pages/flow/v2/layout/FlowLayoutV2RefreshAndLoadMorePage';
import { FlowLayoutV2PositioningPage } from './src/main/ets/pages/flow/v2/layout/FlowLayoutV2PositioningPage';
import { FlowLayoutV2Page } from './src/main/ets/pages/flow/v2/layout/FlowLayoutV2Page';
import { FlowLayoutV2NoSpringPage } from './src/main/ets/pages/flow/v2/layout/FlowLayoutV2NoSpringPage';
import { FlowLayoutV2NoReboundPage } from './src/main/ets/pages/flow/v2/layout/FlowLayoutV2NoReboundPage';
import { FlowLayoutV2NoDataPage } from './src/main/ets/pages/flow/v2/layout/FlowLayoutV2NoDataPage';
import { FlowLayoutV2MaxSpringPage } from './src/main/ets/pages/flow/v2/layout/FlowLayoutV2MaxSpringPage';
import { FlowLayoutV2LoadMorePage } from './src/main/ets/pages/flow/v2/layout/FlowLayoutV2LoadMorePage';
import { FlowLayoutV2LazyRefreshAndLoadMorePage } from './src/main/ets/pages/flow/v2/layout/FlowLayoutV2LazyRefreshAndLoadMorePage';
import { FlowLayoutV2LazyPage } from './src/main/ets/pages/flow/v2/layout/FlowLayoutV2LazyPage';
import { FlowLayoutV2HeaderPage } from './src/main/ets/pages/flow/v2/layout/FlowLayoutV2HeaderPage';
import { FlowLayoutV2HeaderAndFooterPage } from './src/main/ets/pages/flow/v2/layout/FlowLayoutV2HeaderAndFooterPage';
import { FlowLayoutV2FooterPage } from './src/main/ets/pages/flow/v2/layout/FlowLayoutV2FooterPage';
import { FlowLayoutV2FixedBottomPage } from './src/main/ets/pages/flow/v2/layout/FlowLayoutV2FixedBottomPage';
import { FlowLayoutV2EnableSpringPage } from './src/main/ets/pages/flow/v2/layout/FlowLayoutV2EnableSpringPage';
import { FlowLayoutV2AutoRefreshPage } from './src/main/ets/pages/flow/v2/layout/FlowLayoutV2AutoRefreshPage';
import { FlowLayoutV2AutoLoadMorePage } from './src/main/ets/pages/flow/v2/layout/FlowLayoutV2AutoLoadMorePage';
import { FlowLayoutV2AdaptiveTopPage } from './src/main/ets/pages/flow/v2/layout/FlowLayoutV2AdaptiveTopPage';
import { FlowLayoutV2AdaptiveBottomPage } from './src/main/ets/pages/flow/v2/layout/FlowLayoutV2AdaptiveBottomPage';
import { V2SecondFloorExample2 } from './src/main/ets/pages/floor/v2/example2/V2SecondFloorExample2';
import { V2SecondFloorExample } from './src/main/ets/pages/floor/v2/example/V2SecondFloorExample';
import { SecondFloorPageV2 } from './src/main/ets/pages/floor/v2/SecondFloorPageV2';
import { RouterConfig,routerGetBuilderType, routerInitBuilder,NavDestinationView } from '@abner/router';

/**
 * AUTHOR:AbnerMing
 * INTRODUCE:动态配置路径
 * */
function importPath(builderName: string) {
  switch (builderName) {
    case "example_ListV2Index":
      import("./src/main/ets/pages/list/ListV2Index")
      break
    case "example_GridV2Index":
      import("./src/main/ets/pages/grid/GridV2Index")
      break
    case "example_FlowV2Index":
      import("./src/main/ets/pages/flow/FlowV2Index")
      break
    case "example_Rv2WebViewPage":
      import("./src/main/ets/pages/rv/v2/Rv2WebViewPage")
      break
    case "example_Rv2WaterFlowUpAndDownPage":
      import("./src/main/ets/pages/rv/v2/Rv2WaterFlowUpAndDownPage")
      break
    case "example_Rv2RefreshUpAndDownPage":
      import("./src/main/ets/pages/rv/v2/Rv2RefreshUpAndDownPage")
      break
    case "example_Rv2RefreshScrollPage":
      import("./src/main/ets/pages/rv/v2/Rv2RefreshScrollPage")
      break
    case "example_Rv2RefreshPointPage":
      import("./src/main/ets/pages/rv/v2/Rv2RefreshPointPage")
      break
    case "example_Rv2RefreshImmersivePage":
      import("./src/main/ets/pages/rv/v2/Rv2RefreshImmersivePage")
      break
    case "example_Rv2RefreshHeaderAndFooterPage":
      import("./src/main/ets/pages/rv/v2/Rv2RefreshHeaderAndFooterPage")
      break
    case "example_Rv2NoScrollSpringPage":
      import("./src/main/ets/pages/rv/v2/Rv2NoScrollSpringPage")
      break
    case "example_Rv2MultiViewPage":
      import("./src/main/ets/pages/rv/v2/Rv2MultiViewPage")
      break
    case "example_Rv2MaxScrollSpringPage":
      import("./src/main/ets/pages/rv/v2/Rv2MaxScrollSpringPage")
      break
    case "example_Rv2LoadDataSpringBackPage":
      import("./src/main/ets/pages/rv/v2/Rv2LoadDataSpringBackPage")
      break
    case "example_Rv2ListUpAndDownPage":
      import("./src/main/ets/pages/rv/v2/Rv2ListUpAndDownPage")
      break
    case "example_Rv2LazyDataOperationPage":
      import("./src/main/ets/pages/rv/v2/Rv2LazyDataOperationPage")
      break
    case "example_Rv2Index":
      import("./src/main/ets/pages/rv/v2/Rv2Index")
      break
    case "example_Rv2GridUpAndDownPage":
      import("./src/main/ets/pages/rv/v2/Rv2GridUpAndDownPage")
      break
    case "example_Rv2FooterNothingPage":
      import("./src/main/ets/pages/rv/v2/Rv2FooterNothingPage")
      break
    case "example_Rv2FixedFooterPage":
      import("./src/main/ets/pages/rv/v2/Rv2FixedFooterPage")
      break
    case "example_Rv2AutoRefreshPage":
      import("./src/main/ets/pages/rv/v2/Rv2AutoRefreshPage")
      break
    case "example_Rv2AutoListUpAndDownPage":
      import("./src/main/ets/pages/rv/v2/Rv2AutoListUpAndDownPage")
      break
    case "example_Rv2AdaptiveHeightPage":
      import("./src/main/ets/pages/rv/v2/Rv2AdaptiveHeightPage")
      break
    case "example_LitheV2WebViewPage":
      import("./src/main/ets/pages/lithe/v2/LitheV2WebViewPage")
      break
    case "example_LitheV2WaterFlowUpAndDownPage":
      import("./src/main/ets/pages/lithe/v2/LitheV2WaterFlowUpAndDownPage")
      break
    case "example_LitheV2RefreshUpAndDownPage":
      import("./src/main/ets/pages/lithe/v2/LitheV2RefreshUpAndDownPage")
      break
    case "example_LitheV2RefreshScrollPage":
      import("./src/main/ets/pages/lithe/v2/LitheV2RefreshScrollPage")
      break
    case "example_LitheV2RefreshPointPage":
      import("./src/main/ets/pages/lithe/v2/LitheV2RefreshPointPage")
      break
    case "example_LitheV2RefreshImmersivePage":
      import("./src/main/ets/pages/lithe/v2/LitheV2RefreshImmersivePage")
      break
    case "example_LitheV2RefreshHeaderAndFooterPage":
      import("./src/main/ets/pages/lithe/v2/LitheV2RefreshHeaderAndFooterPage")
      break
    case "example_LitheV2NoScrollSpringPage":
      import("./src/main/ets/pages/lithe/v2/LitheV2NoScrollSpringPage")
      break
    case "example_LitheV2MultiViewPage":
      import("./src/main/ets/pages/lithe/v2/LitheV2MultiViewPage")
      break
    case "example_LitheV2LoadDataSpringBackPage":
      import("./src/main/ets/pages/lithe/v2/LitheV2LoadDataSpringBackPage")
      break
    case "example_LitheV2ListUpAndDownPage":
      import("./src/main/ets/pages/lithe/v2/LitheV2ListUpAndDownPage")
      break
    case "example_LitheV2ListMaxSpringPage":
      import("./src/main/ets/pages/lithe/v2/LitheV2ListMaxSpringPage")
      break
    case "example_LitheV2LazyDataOperationPage":
      import("./src/main/ets/pages/lithe/v2/LitheV2LazyDataOperationPage")
      break
    case "example_LitheV2LayoutHeaderPage":
      import("./src/main/ets/pages/lithe/v2/LitheV2LayoutHeaderPage")
      break
    case "example_LitheV2Index":
      import("./src/main/ets/pages/lithe/v2/LitheV2Index")
      break
    case "example_LitheV2GridUpAndDownPage":
      import("./src/main/ets/pages/lithe/v2/LitheV2GridUpAndDownPage")
      break
    case "example_LitheV2FooterNothingPage":
      import("./src/main/ets/pages/lithe/v2/LitheV2FooterNothingPage")
      break
    case "example_LitheV2FixedFooterPage":
      import("./src/main/ets/pages/lithe/v2/LitheV2FixedFooterPage")
      break
    case "example_LitheV2AutoRefreshPage":
      import("./src/main/ets/pages/lithe/v2/LitheV2AutoRefreshPage")
      break
    case "example_LitheV2AutoListUpAndDownPage":
      import("./src/main/ets/pages/lithe/v2/LitheV2AutoListUpAndDownPage")
      break
    case "example_LitheV2AdaptiveHeightPage":
      import("./src/main/ets/pages/lithe/v2/LitheV2AdaptiveHeightPage")
      break
    case "example_ListViewV2UpAndDownPage":
      import("./src/main/ets/pages/list/v2/view/ListViewV2UpAndDownPage")
      break
    case "example_ListViewV2UpAndDownLazyPage":
      import("./src/main/ets/pages/list/v2/view/ListViewV2UpAndDownLazyPage")
      break
    case "example_ListViewV2TabsPage":
      import("./src/main/ets/pages/list/v2/view/ListViewV2TabsPage")
      break
    case "example_ListViewV2SwipeActionPage":
      import("./src/main/ets/pages/list/v2/view/ListViewV2SwipeActionPage")
      break
    case "example_ListViewV2StickyTopPage":
      import("./src/main/ets/pages/list/v2/view/ListViewV2StickyTopPage")
      break
    case "example_ListViewV2StickyRLTopPage":
      import("./src/main/ets/pages/list/v2/view/ListViewV2StickyRLTopPage")
      break
    case "example_ListViewV2StickLayoutPage":
      import("./src/main/ets/pages/list/v2/view/ListViewV2StickLayoutPage")
      break
    case "example_ListViewV2SpringRatioPage":
      import("./src/main/ets/pages/list/v2/view/ListViewV2SpringRatioPage")
      break
    case "example_ListViewV2SlideDeletePage":
      import("./src/main/ets/pages/list/v2/view/ListViewV2SlideDeletePage")
      break
    case "example_ListViewV2RefreshPage":
      import("./src/main/ets/pages/list/v2/view/ListViewV2RefreshPage")
      break
    case "example_ListViewV2RefreshHeaderFooterPage":
      import("./src/main/ets/pages/list/v2/view/ListViewV2RefreshHeaderFooterPage")
      break
    case "example_ListViewV2PositioningPage":
      import("./src/main/ets/pages/list/v2/view/ListViewV2PositioningPage")
      break
    case "example_ListViewV2Page":
      import("./src/main/ets/pages/list/v2/view/ListViewV2Page")
      break
    case "example_ListViewV2NoSpringPage":
      import("./src/main/ets/pages/list/v2/view/ListViewV2NoSpringPage")
      break
    case "example_ListViewV2NoReboundPage":
      import("./src/main/ets/pages/list/v2/view/ListViewV2NoReboundPage")
      break
    case "example_ListViewV2NoDataPage":
      import("./src/main/ets/pages/list/v2/view/ListViewV2NoDataPage")
      break
    case "example_ListViewV2MaxSpringPage":
      import("./src/main/ets/pages/list/v2/view/ListViewV2MaxSpringPage")
      break
    case "example_ListViewV2LoadMorePage":
      import("./src/main/ets/pages/list/v2/view/ListViewV2LoadMorePage")
      break
    case "example_ListViewV2LazyPage":
      import("./src/main/ets/pages/list/v2/view/ListViewV2LazyPage")
      break
    case "example_ListViewV2LazyDataOperationPage":
      import("./src/main/ets/pages/list/v2/view/ListViewV2LazyDataOperationPage")
      break
    case "example_ListViewV2ItemGroupPage":
      import("./src/main/ets/pages/list/v2/view/ListViewV2ItemGroupPage")
      break
    case "example_ListViewV2ItemGroupNoStickyPage":
      import("./src/main/ets/pages/list/v2/view/ListViewV2ItemGroupNoStickyPage")
      break
    case "example_ListViewV2ItemGroupIndexPage":
      import("./src/main/ets/pages/list/v2/view/ListViewV2ItemGroupIndexPage")
      break
    case "example_ListViewV2HeaderPage":
      import("./src/main/ets/pages/list/v2/view/ListViewV2HeaderPage")
      break
    case "example_ListViewV2HeaderAndFooterPage":
      import("./src/main/ets/pages/list/v2/view/ListViewV2HeaderAndFooterPage")
      break
    case "example_ListViewV2FooterPage":
      import("./src/main/ets/pages/list/v2/view/ListViewV2FooterPage")
      break
    case "example_ListViewV2FixedBottomLoadPage":
      import("./src/main/ets/pages/list/v2/view/ListViewV2FixedBottomLoadPage")
      break
    case "example_ListViewV2ErrorOrEmptyPage":
      import("./src/main/ets/pages/list/v2/view/ListViewV2ErrorOrEmptyPage")
      break
    case "example_ListViewV2EnableSpringPage":
      import("./src/main/ets/pages/list/v2/view/ListViewV2EnableSpringPage")
      break
    case "example_ListViewV2DataOperationPage":
      import("./src/main/ets/pages/list/v2/view/ListViewV2DataOperationPage")
      break
    case "example_ListViewV2AutoRefreshPage":
      import("./src/main/ets/pages/list/v2/view/ListViewV2AutoRefreshPage")
      break
    case "example_ListViewV2AutoLoadMorePage":
      import("./src/main/ets/pages/list/v2/view/ListViewV2AutoLoadMorePage")
      break
    case "example_ListViewV2ArbitrarilyStickyTopPage":
      import("./src/main/ets/pages/list/v2/view/ListViewV2ArbitrarilyStickyTopPage")
      break
    case "example_ListViewV2AdaptivePage2":
      import("./src/main/ets/pages/list/v2/view/ListViewV2AdaptivePage2")
      break
    case "example_ListViewV2AdaptivePage":
      import("./src/main/ets/pages/list/v2/view/ListViewV2AdaptivePage")
      break
    case "example_ListLayoutV2UpAndDownPage":
      import("./src/main/ets/pages/list/v2/layout/ListLayoutV2UpAndDownPage")
      break
    case "example_ListLayoutV2TabsPage":
      import("./src/main/ets/pages/list/v2/layout/ListLayoutV2TabsPage")
      break
    case "example_ListLayoutV2SwipeActionPage":
      import("./src/main/ets/pages/list/v2/layout/ListLayoutV2SwipeActionPage")
      break
    case "example_ListLayoutV2StickyTopRefreshPage":
      import("./src/main/ets/pages/list/v2/layout/ListLayoutV2StickyTopRefreshPage")
      break
    case "example_ListLayoutV2StickyTopPage":
      import("./src/main/ets/pages/list/v2/layout/ListLayoutV2StickyTopPage")
      break
    case "example_ListLayoutV2StickPage":
      import("./src/main/ets/pages/list/v2/layout/ListLayoutV2StickPage")
      break
    case "example_ListLayoutV2SpringRatioPage":
      import("./src/main/ets/pages/list/v2/layout/ListLayoutV2SpringRatioPage")
      break
    case "example_ListLayoutV2SlideDeletePage":
      import("./src/main/ets/pages/list/v2/layout/ListLayoutV2SlideDeletePage")
      break
    case "example_ListLayoutV2RefreshPage":
      import("./src/main/ets/pages/list/v2/layout/ListLayoutV2RefreshPage")
      break
    case "example_ListLayoutV2RefreshHeaderFooterPage":
      import("./src/main/ets/pages/list/v2/layout/ListLayoutV2RefreshHeaderFooterPage")
      break
    case "example_ListLayoutV2PositioningPage":
      import("./src/main/ets/pages/list/v2/layout/ListLayoutV2PositioningPage")
      break
    case "example_ListLayoutV2Page":
      import("./src/main/ets/pages/list/v2/layout/ListLayoutV2Page")
      break
    case "example_ListLayoutV2NoSpringPage":
      import("./src/main/ets/pages/list/v2/layout/ListLayoutV2NoSpringPage")
      break
    case "example_ListLayoutV2NoReboundPage":
      import("./src/main/ets/pages/list/v2/layout/ListLayoutV2NoReboundPage")
      break
    case "example_ListLayoutV2MaxSpringPage":
      import("./src/main/ets/pages/list/v2/layout/ListLayoutV2MaxSpringPage")
      break
    case "example_ListLayoutV2LoadMorePage":
      import("./src/main/ets/pages/list/v2/layout/ListLayoutV2LoadMorePage")
      break
    case "example_ListLayoutV2LazyUpAndDownPage":
      import("./src/main/ets/pages/list/v2/layout/ListLayoutV2LazyUpAndDownPage")
      break
    case "example_ListLayoutV2LazyPage":
      import("./src/main/ets/pages/list/v2/layout/ListLayoutV2LazyPage")
      break
    case "example_ListLayoutV2LazyDataOperationPage":
      import("./src/main/ets/pages/list/v2/layout/ListLayoutV2LazyDataOperationPage")
      break
    case "example_ListLayoutV2ItemGroupPage":
      import("./src/main/ets/pages/list/v2/layout/ListLayoutV2ItemGroupPage")
      break
    case "example_ListLayoutV2ItemGroupNoStickyPage":
      import("./src/main/ets/pages/list/v2/layout/ListLayoutV2ItemGroupNoStickyPage")
      break
    case "example_ListLayoutV2ItemGroupIndexPage":
      import("./src/main/ets/pages/list/v2/layout/ListLayoutV2ItemGroupIndexPage")
      break
    case "example_ListLayoutV2HeaderPage":
      import("./src/main/ets/pages/list/v2/layout/ListLayoutV2HeaderPage")
      break
    case "example_ListLayoutV2HeaderAndFooterPage":
      import("./src/main/ets/pages/list/v2/layout/ListLayoutV2HeaderAndFooterPage")
      break
    case "example_ListLayoutV2FooterPage":
      import("./src/main/ets/pages/list/v2/layout/ListLayoutV2FooterPage")
      break
    case "example_ListLayoutV2FixedFooterPage":
      import("./src/main/ets/pages/list/v2/layout/ListLayoutV2FixedFooterPage")
      break
    case "example_ListLayoutV2FixedBottomLoadPage":
      import("./src/main/ets/pages/list/v2/layout/ListLayoutV2FixedBottomLoadPage")
      break
    case "example_ListLayoutV2ErrorOrEmptyPage":
      import("./src/main/ets/pages/list/v2/layout/ListLayoutV2ErrorOrEmptyPage")
      break
    case "example_ListLayoutV2EnableSpringPage":
      import("./src/main/ets/pages/list/v2/layout/ListLayoutV2EnableSpringPage")
      break
    case "example_ListLayoutV2DataOperationPage":
      import("./src/main/ets/pages/list/v2/layout/ListLayoutV2DataOperationPage")
      break
    case "example_ListLayoutV2AutoRefreshPage":
      import("./src/main/ets/pages/list/v2/layout/ListLayoutV2AutoRefreshPage")
      break
    case "example_ListLayoutV2AutoLoadMorePage":
      import("./src/main/ets/pages/list/v2/layout/ListLayoutV2AutoLoadMorePage")
      break
    case "example_ListLayoutV2ArbitrarilyStickyTopPage":
      import("./src/main/ets/pages/list/v2/layout/ListLayoutV2ArbitrarilyStickyTopPage")
      break
    case "example_ListLayoutV2AdaptivePage2":
      import("./src/main/ets/pages/list/v2/layout/ListLayoutV2AdaptivePage2")
      break
    case "example_ListLayoutV2AdaptivePage":
      import("./src/main/ets/pages/list/v2/layout/ListLayoutV2AdaptivePage")
      break
    case "example_GridViewV2TabsPage":
      import("./src/main/ets/pages/grid/v2/view/GridViewV2TabsPage")
      break
    case "example_GridViewV2StickyTopPage":
      import("./src/main/ets/pages/grid/v2/view/GridViewV2StickyTopPage")
      break
    case "example_GridViewV2StickyRLTopPage":
      import("./src/main/ets/pages/grid/v2/view/GridViewV2StickyRLTopPage")
      break
    case "example_GridViewV2StickLayoutViewPage":
      import("./src/main/ets/pages/grid/v2/view/GridViewV2StickLayoutViewPage")
      break
    case "example_GridViewV2SpringRatioPage":
      import("./src/main/ets/pages/grid/v2/view/GridViewV2SpringRatioPage")
      break
    case "example_GridViewV2RefreshPage":
      import("./src/main/ets/pages/grid/v2/view/GridViewV2RefreshPage")
      break
    case "example_GridViewV2RefreshHeaderFooterPage":
      import("./src/main/ets/pages/grid/v2/view/GridViewV2RefreshHeaderFooterPage")
      break
    case "example_GridViewV2RefreshAndLoadPage":
      import("./src/main/ets/pages/grid/v2/view/GridViewV2RefreshAndLoadPage")
      break
    case "example_GridViewV2PositioningPage":
      import("./src/main/ets/pages/grid/v2/view/GridViewV2PositioningPage")
      break
    case "example_GridViewV2Page":
      import("./src/main/ets/pages/grid/v2/view/GridViewV2Page")
      break
    case "example_GridViewV2NoSpringPage":
      import("./src/main/ets/pages/grid/v2/view/GridViewV2NoSpringPage")
      break
    case "example_GridViewV2NoReboundPage":
      import("./src/main/ets/pages/grid/v2/view/GridViewV2NoReboundPage")
      break
    case "example_GridViewV2NoDataPage":
      import("./src/main/ets/pages/grid/v2/view/GridViewV2NoDataPage")
      break
    case "example_GridViewV2MaxSpringPage":
      import("./src/main/ets/pages/grid/v2/view/GridViewV2MaxSpringPage")
      break
    case "example_GridViewV2LoadMorePage":
      import("./src/main/ets/pages/grid/v2/view/GridViewV2LoadMorePage")
      break
    case "example_GridViewV2LazyRefreshAndLoadPage":
      import("./src/main/ets/pages/grid/v2/view/GridViewV2LazyRefreshAndLoadPage")
      break
    case "example_GridViewV2LazyPage":
      import("./src/main/ets/pages/grid/v2/view/GridViewV2LazyPage")
      break
    case "example_GridViewV2HeaderPage":
      import("./src/main/ets/pages/grid/v2/view/GridViewV2HeaderPage")
      break
    case "example_GridViewV2HeaderAndFooterPage":
      import("./src/main/ets/pages/grid/v2/view/GridViewV2HeaderAndFooterPage")
      break
    case "example_GridViewV2FooterPage":
      import("./src/main/ets/pages/grid/v2/view/GridViewV2FooterPage")
      break
    case "example_GridViewV2FixedBottomLoadPage":
      import("./src/main/ets/pages/grid/v2/view/GridViewV2FixedBottomLoadPage")
      break
    case "example_GridViewV2EnableSpringPage":
      import("./src/main/ets/pages/grid/v2/view/GridViewV2EnableSpringPage")
      break
    case "example_GridViewV2AutoRefreshPage":
      import("./src/main/ets/pages/grid/v2/view/GridViewV2AutoRefreshPage")
      break
    case "example_GridViewV2AutoLoadMorePage":
      import("./src/main/ets/pages/grid/v2/view/GridViewV2AutoLoadMorePage")
      break
    case "example_GridViewV2ArbitrarilyStickyTopPage":
      import("./src/main/ets/pages/grid/v2/view/GridViewV2ArbitrarilyStickyTopPage")
      break
    case "example_GridViewV2AdaptiveTopPage":
      import("./src/main/ets/pages/grid/v2/view/GridViewV2AdaptiveTopPage")
      break
    case "example_GridViewV2AdaptiveBottomPage":
      import("./src/main/ets/pages/grid/v2/view/GridViewV2AdaptiveBottomPage")
      break
    case "example_GridV2DropPage":
      import("./src/main/ets/pages/grid/v2/view/GridV2DropPage")
      break
    case "example_GridLayoutV2TabsPage":
      import("./src/main/ets/pages/grid/v2/layout/GridLayoutV2TabsPage")
      break
    case "example_GridLayoutV2StickyTopPage":
      import("./src/main/ets/pages/grid/v2/layout/GridLayoutV2StickyTopPage")
      break
    case "example_GridLayoutV2StickyRLTopPage":
      import("./src/main/ets/pages/grid/v2/layout/GridLayoutV2StickyRLTopPage")
      break
    case "example_GridLayoutV2StickLayoutViewPage":
      import("./src/main/ets/pages/grid/v2/layout/GridLayoutV2StickLayoutViewPage")
      break
    case "example_GridLayoutV2SpringRatioPage":
      import("./src/main/ets/pages/grid/v2/layout/GridLayoutV2SpringRatioPage")
      break
    case "example_GridLayoutV2RefreshPage":
      import("./src/main/ets/pages/grid/v2/layout/GridLayoutV2RefreshPage")
      break
    case "example_GridLayoutV2RefreshHeaderFooterPage":
      import("./src/main/ets/pages/grid/v2/layout/GridLayoutV2RefreshHeaderFooterPage")
      break
    case "example_GridLayoutV2RefreshAndLoadPage":
      import("./src/main/ets/pages/grid/v2/layout/GridLayoutV2RefreshAndLoadPage")
      break
    case "example_GridLayoutV2PositioningPage":
      import("./src/main/ets/pages/grid/v2/layout/GridLayoutV2PositioningPage")
      break
    case "example_GridLayoutV2Page":
      import("./src/main/ets/pages/grid/v2/layout/GridLayoutV2Page")
      break
    case "example_GridLayoutV2NoSpringPage":
      import("./src/main/ets/pages/grid/v2/layout/GridLayoutV2NoSpringPage")
      break
    case "example_GridLayoutV2NoReboundPage":
      import("./src/main/ets/pages/grid/v2/layout/GridLayoutV2NoReboundPage")
      break
    case "example_GridLayoutV2NoDataPage":
      import("./src/main/ets/pages/grid/v2/layout/GridLayoutV2NoDataPage")
      break
    case "example_GridLayoutV2MaxSpringPage":
      import("./src/main/ets/pages/grid/v2/layout/GridLayoutV2MaxSpringPage")
      break
    case "example_GridLayoutV2LoadMorePage":
      import("./src/main/ets/pages/grid/v2/layout/GridLayoutV2LoadMorePage")
      break
    case "example_GridLayoutV2LazyRefreshAndLoadPage":
      import("./src/main/ets/pages/grid/v2/layout/GridLayoutV2LazyRefreshAndLoadPage")
      break
    case "example_GridLayoutV2LazyPage":
      import("./src/main/ets/pages/grid/v2/layout/GridLayoutV2LazyPage")
      break
    case "example_GridLayoutV2HeaderPage":
      import("./src/main/ets/pages/grid/v2/layout/GridLayoutV2HeaderPage")
      break
    case "example_GridLayoutV2HeaderAndFooterPage":
      import("./src/main/ets/pages/grid/v2/layout/GridLayoutV2HeaderAndFooterPage")
      break
    case "example_GridLayoutV2FooterPage":
      import("./src/main/ets/pages/grid/v2/layout/GridLayoutV2FooterPage")
      break
    case "example_GridLayoutV2FixedBottomLoadPage":
      import("./src/main/ets/pages/grid/v2/layout/GridLayoutV2FixedBottomLoadPage")
      break
    case "example_GridLayoutV2EnableSpringPage":
      import("./src/main/ets/pages/grid/v2/layout/GridLayoutV2EnableSpringPage")
      break
    case "example_GridLayoutV2AutoRefreshPage":
      import("./src/main/ets/pages/grid/v2/layout/GridLayoutV2AutoRefreshPage")
      break
    case "example_GridLayoutV2AutoLoadMorePage":
      import("./src/main/ets/pages/grid/v2/layout/GridLayoutV2AutoLoadMorePage")
      break
    case "example_GridLayoutV2ArbitrarilyStickyTopPage":
      import("./src/main/ets/pages/grid/v2/layout/GridLayoutV2ArbitrarilyStickyTopPage")
      break
    case "example_GridLayoutV2AdaptiveTopPage":
      import("./src/main/ets/pages/grid/v2/layout/GridLayoutV2AdaptiveTopPage")
      break
    case "example_GridLayoutV2AdaptiveBottomPage":
      import("./src/main/ets/pages/grid/v2/layout/GridLayoutV2AdaptiveBottomPage")
      break
    case "example_FlowViewV2TopActionBarPage":
      import("./src/main/ets/pages/flow/v2/view/FlowViewV2TopActionBarPage")
      break
    case "example_FlowViewV2TabsPage":
      import("./src/main/ets/pages/flow/v2/view/FlowViewV2TabsPage")
      break
    case "example_FlowViewV2StickyTopPage":
      import("./src/main/ets/pages/flow/v2/view/FlowViewV2StickyTopPage")
      break
    case "example_FlowViewV2StickyTopActionBarPage":
      import("./src/main/ets/pages/flow/v2/view/FlowViewV2StickyTopActionBarPage")
      break
    case "example_FlowViewV2StickyRLTopPage":
      import("./src/main/ets/pages/flow/v2/view/FlowViewV2StickyRLTopPage")
      break
    case "example_FlowViewV2SpringRatioPage":
      import("./src/main/ets/pages/flow/v2/view/FlowViewV2SpringRatioPage")
      break
    case "example_FlowViewV2RefreshPage":
      import("./src/main/ets/pages/flow/v2/view/FlowViewV2RefreshPage")
      break
    case "example_FlowViewV2RefreshHeaderAndFooterPage":
      import("./src/main/ets/pages/flow/v2/view/FlowViewV2RefreshHeaderAndFooterPage")
      break
    case "example_FlowViewV2RefreshAndLoadMorePage":
      import("./src/main/ets/pages/flow/v2/view/FlowViewV2RefreshAndLoadMorePage")
      break
    case "example_FlowViewV2PositioningPage":
      import("./src/main/ets/pages/flow/v2/view/FlowViewV2PositioningPage")
      break
    case "example_FlowViewV2Page":
      import("./src/main/ets/pages/flow/v2/view/FlowViewV2Page")
      break
    case "example_FlowViewV2NoSpringPage":
      import("./src/main/ets/pages/flow/v2/view/FlowViewV2NoSpringPage")
      break
    case "example_FlowViewV2NoReboundPage":
      import("./src/main/ets/pages/flow/v2/view/FlowViewV2NoReboundPage")
      break
    case "example_FlowViewV2NoDataPage":
      import("./src/main/ets/pages/flow/v2/view/FlowViewV2NoDataPage")
      break
    case "example_FlowViewV2MaxSpringPage":
      import("./src/main/ets/pages/flow/v2/view/FlowViewV2MaxSpringPage")
      break
    case "example_FlowViewV2LoadMorePage":
      import("./src/main/ets/pages/flow/v2/view/FlowViewV2LoadMorePage")
      break
    case "example_FlowViewV2LazyRefreshAndLoadMorePage":
      import("./src/main/ets/pages/flow/v2/view/FlowViewV2LazyRefreshAndLoadMorePage")
      break
    case "example_FlowViewV2LazyPage":
      import("./src/main/ets/pages/flow/v2/view/FlowViewV2LazyPage")
      break
    case "example_FlowViewV2HeaderPage":
      import("./src/main/ets/pages/flow/v2/view/FlowViewV2HeaderPage")
      break
    case "example_FlowViewV2HeaderAndFooterPage":
      import("./src/main/ets/pages/flow/v2/view/FlowViewV2HeaderAndFooterPage")
      break
    case "example_FlowViewV2FooterPage":
      import("./src/main/ets/pages/flow/v2/view/FlowViewV2FooterPage")
      break
    case "example_FlowViewV2FixedBottomPage":
      import("./src/main/ets/pages/flow/v2/view/FlowViewV2FixedBottomPage")
      break
    case "example_FlowViewV2EnableSpringPage":
      import("./src/main/ets/pages/flow/v2/view/FlowViewV2EnableSpringPage")
      break
    case "example_FlowViewV2AutoRefreshPage":
      import("./src/main/ets/pages/flow/v2/view/FlowViewV2AutoRefreshPage")
      break
    case "example_FlowViewV2AutoLoadMorePage":
      import("./src/main/ets/pages/flow/v2/view/FlowViewV2AutoLoadMorePage")
      break
    case "example_FlowViewV2ArbitrarilyStickyTopPage":
      import("./src/main/ets/pages/flow/v2/view/FlowViewV2ArbitrarilyStickyTopPage")
      break
    case "example_FlowViewV2AdaptiveTopPage":
      import("./src/main/ets/pages/flow/v2/view/FlowViewV2AdaptiveTopPage")
      break
    case "example_FlowViewV2AdaptiveBottomPage":
      import("./src/main/ets/pages/flow/v2/view/FlowViewV2AdaptiveBottomPage")
      break
    case "example_FlowLayoutV2TopActionBarPage":
      import("./src/main/ets/pages/flow/v2/layout/FlowLayoutV2TopActionBarPage")
      break
    case "example_FlowLayoutV2TabsPage":
      import("./src/main/ets/pages/flow/v2/layout/FlowLayoutV2TabsPage")
      break
    case "example_FlowLayoutV2StickyTopPage":
      import("./src/main/ets/pages/flow/v2/layout/FlowLayoutV2StickyTopPage")
      break
    case "example_FlowLayoutV2StickyRLTopPage":
      import("./src/main/ets/pages/flow/v2/layout/FlowLayoutV2StickyRLTopPage")
      break
    case "example_FlowLayoutV2SpringRatioPage":
      import("./src/main/ets/pages/flow/v2/layout/FlowLayoutV2SpringRatioPage")
      break
    case "example_FlowLayoutV2RefreshPage":
      import("./src/main/ets/pages/flow/v2/layout/FlowLayoutV2RefreshPage")
      break
    case "example_FlowLayoutV2RefreshHeaderAndFooterPage":
      import("./src/main/ets/pages/flow/v2/layout/FlowLayoutV2RefreshHeaderAndFooterPage")
      break
    case "example_FlowLayoutV2RefreshAndLoadMorePage":
      import("./src/main/ets/pages/flow/v2/layout/FlowLayoutV2RefreshAndLoadMorePage")
      break
    case "example_FlowLayoutV2PositioningPage":
      import("./src/main/ets/pages/flow/v2/layout/FlowLayoutV2PositioningPage")
      break
    case "example_FlowLayoutV2Page":
      import("./src/main/ets/pages/flow/v2/layout/FlowLayoutV2Page")
      break
    case "example_FlowLayoutV2NoSpringPage":
      import("./src/main/ets/pages/flow/v2/layout/FlowLayoutV2NoSpringPage")
      break
    case "example_FlowLayoutV2NoReboundPage":
      import("./src/main/ets/pages/flow/v2/layout/FlowLayoutV2NoReboundPage")
      break
    case "example_FlowLayoutV2NoDataPage":
      import("./src/main/ets/pages/flow/v2/layout/FlowLayoutV2NoDataPage")
      break
    case "example_FlowLayoutV2MaxSpringPage":
      import("./src/main/ets/pages/flow/v2/layout/FlowLayoutV2MaxSpringPage")
      break
    case "example_FlowLayoutV2LoadMorePage":
      import("./src/main/ets/pages/flow/v2/layout/FlowLayoutV2LoadMorePage")
      break
    case "example_FlowLayoutV2LazyRefreshAndLoadMorePage":
      import("./src/main/ets/pages/flow/v2/layout/FlowLayoutV2LazyRefreshAndLoadMorePage")
      break
    case "example_FlowLayoutV2LazyPage":
      import("./src/main/ets/pages/flow/v2/layout/FlowLayoutV2LazyPage")
      break
    case "example_FlowLayoutV2HeaderPage":
      import("./src/main/ets/pages/flow/v2/layout/FlowLayoutV2HeaderPage")
      break
    case "example_FlowLayoutV2HeaderAndFooterPage":
      import("./src/main/ets/pages/flow/v2/layout/FlowLayoutV2HeaderAndFooterPage")
      break
    case "example_FlowLayoutV2FooterPage":
      import("./src/main/ets/pages/flow/v2/layout/FlowLayoutV2FooterPage")
      break
    case "example_FlowLayoutV2FixedBottomPage":
      import("./src/main/ets/pages/flow/v2/layout/FlowLayoutV2FixedBottomPage")
      break
    case "example_FlowLayoutV2EnableSpringPage":
      import("./src/main/ets/pages/flow/v2/layout/FlowLayoutV2EnableSpringPage")
      break
    case "example_FlowLayoutV2AutoRefreshPage":
      import("./src/main/ets/pages/flow/v2/layout/FlowLayoutV2AutoRefreshPage")
      break
    case "example_FlowLayoutV2AutoLoadMorePage":
      import("./src/main/ets/pages/flow/v2/layout/FlowLayoutV2AutoLoadMorePage")
      break
    case "example_FlowLayoutV2AdaptiveTopPage":
      import("./src/main/ets/pages/flow/v2/layout/FlowLayoutV2AdaptiveTopPage")
      break
    case "example_FlowLayoutV2AdaptiveBottomPage":
      import("./src/main/ets/pages/flow/v2/layout/FlowLayoutV2AdaptiveBottomPage")
      break
    case "example_V2SecondFloorExample2":
      import("./src/main/ets/pages/floor/v2/example2/V2SecondFloorExample2")
      break
    case "example_V2SecondFloorExample":
      import("./src/main/ets/pages/floor/v2/example/V2SecondFloorExample")
      break
    case "example_SecondFloorPageV2":
      import("./src/main/ets/pages/floor/v2/SecondFloorPageV2")
      break

  }
}

/**
 * AUTHOR:AbnerMing
 * INTRODUCE:动态配置组件
 * */
@Builder
export function viewBuilder(params?:Object) {
  NavDestinationView() {
    if (routerGetBuilderType() == "example_ListV2Index") {
      ListV2Index()
    } else 
    if (routerGetBuilderType() == "example_GridV2Index") {
      GridV2Index()
    } else 
    if (routerGetBuilderType() == "example_FlowV2Index") {
      FlowV2Index()
    } else 
    if (routerGetBuilderType() == "example_Rv2WebViewPage") {
      Rv2WebViewPage()
    } else 
    if (routerGetBuilderType() == "example_Rv2WaterFlowUpAndDownPage") {
      Rv2WaterFlowUpAndDownPage()
    } else 
    if (routerGetBuilderType() == "example_Rv2RefreshUpAndDownPage") {
      Rv2RefreshUpAndDownPage()
    } else 
    if (routerGetBuilderType() == "example_Rv2RefreshScrollPage") {
      Rv2RefreshScrollPage()
    } else 
    if (routerGetBuilderType() == "example_Rv2RefreshPointPage") {
      Rv2RefreshPointPage()
    } else 
    if (routerGetBuilderType() == "example_Rv2RefreshImmersivePage") {
      Rv2RefreshImmersivePage()
    } else 
    if (routerGetBuilderType() == "example_Rv2RefreshHeaderAndFooterPage") {
      Rv2RefreshHeaderAndFooterPage()
    } else 
    if (routerGetBuilderType() == "example_Rv2NoScrollSpringPage") {
      Rv2NoScrollSpringPage()
    } else 
    if (routerGetBuilderType() == "example_Rv2MultiViewPage") {
      Rv2MultiViewPage()
    } else 
    if (routerGetBuilderType() == "example_Rv2MaxScrollSpringPage") {
      Rv2MaxScrollSpringPage()
    } else 
    if (routerGetBuilderType() == "example_Rv2LoadDataSpringBackPage") {
      Rv2LoadDataSpringBackPage()
    } else 
    if (routerGetBuilderType() == "example_Rv2ListUpAndDownPage") {
      Rv2ListUpAndDownPage()
    } else 
    if (routerGetBuilderType() == "example_Rv2LazyDataOperationPage") {
      Rv2LazyDataOperationPage()
    } else 
    if (routerGetBuilderType() == "example_Rv2Index") {
      Rv2Index()
    } else 
    if (routerGetBuilderType() == "example_Rv2GridUpAndDownPage") {
      Rv2GridUpAndDownPage()
    } else 
    if (routerGetBuilderType() == "example_Rv2FooterNothingPage") {
      Rv2FooterNothingPage()
    } else 
    if (routerGetBuilderType() == "example_Rv2FixedFooterPage") {
      Rv2FixedFooterPage()
    } else 
    if (routerGetBuilderType() == "example_Rv2AutoRefreshPage") {
      Rv2AutoRefreshPage()
    } else 
    if (routerGetBuilderType() == "example_Rv2AutoListUpAndDownPage") {
      Rv2AutoListUpAndDownPage()
    } else 
    if (routerGetBuilderType() == "example_Rv2AdaptiveHeightPage") {
      Rv2AdaptiveHeightPage()
    } else 
    if (routerGetBuilderType() == "example_LitheV2WebViewPage") {
      LitheV2WebViewPage()
    } else 
    if (routerGetBuilderType() == "example_LitheV2WaterFlowUpAndDownPage") {
      LitheV2WaterFlowUpAndDownPage()
    } else 
    if (routerGetBuilderType() == "example_LitheV2RefreshUpAndDownPage") {
      LitheV2RefreshUpAndDownPage()
    } else 
    if (routerGetBuilderType() == "example_LitheV2RefreshScrollPage") {
      LitheV2RefreshScrollPage()
    } else 
    if (routerGetBuilderType() == "example_LitheV2RefreshPointPage") {
      LitheV2RefreshPointPage()
    } else 
    if (routerGetBuilderType() == "example_LitheV2RefreshImmersivePage") {
      LitheV2RefreshImmersivePage()
    } else 
    if (routerGetBuilderType() == "example_LitheV2RefreshHeaderAndFooterPage") {
      LitheV2RefreshHeaderAndFooterPage()
    } else 
    if (routerGetBuilderType() == "example_LitheV2NoScrollSpringPage") {
      LitheV2NoScrollSpringPage()
    } else 
    if (routerGetBuilderType() == "example_LitheV2MultiViewPage") {
      LitheV2MultiViewPage()
    } else 
    if (routerGetBuilderType() == "example_LitheV2LoadDataSpringBackPage") {
      LitheV2LoadDataSpringBackPage()
    } else 
    if (routerGetBuilderType() == "example_LitheV2ListUpAndDownPage") {
      LitheV2ListUpAndDownPage()
    } else 
    if (routerGetBuilderType() == "example_LitheV2ListMaxSpringPage") {
      LitheV2ListMaxSpringPage()
    } else 
    if (routerGetBuilderType() == "example_LitheV2LazyDataOperationPage") {
      LitheV2LazyDataOperationPage()
    } else 
    if (routerGetBuilderType() == "example_LitheV2LayoutHeaderPage") {
      LitheV2LayoutHeaderPage()
    } else 
    if (routerGetBuilderType() == "example_LitheV2Index") {
      LitheV2Index()
    } else 
    if (routerGetBuilderType() == "example_LitheV2GridUpAndDownPage") {
      LitheV2GridUpAndDownPage()
    } else 
    if (routerGetBuilderType() == "example_LitheV2FooterNothingPage") {
      LitheV2FooterNothingPage()
    } else 
    if (routerGetBuilderType() == "example_LitheV2FixedFooterPage") {
      LitheV2FixedFooterPage()
    } else 
    if (routerGetBuilderType() == "example_LitheV2AutoRefreshPage") {
      LitheV2AutoRefreshPage()
    } else 
    if (routerGetBuilderType() == "example_LitheV2AutoListUpAndDownPage") {
      LitheV2AutoListUpAndDownPage()
    } else 
    if (routerGetBuilderType() == "example_LitheV2AdaptiveHeightPage") {
      LitheV2AdaptiveHeightPage()
    } else 
    if (routerGetBuilderType() == "example_ListViewV2UpAndDownPage") {
      ListViewV2UpAndDownPage()
    } else 
    if (routerGetBuilderType() == "example_ListViewV2UpAndDownLazyPage") {
      ListViewV2UpAndDownLazyPage()
    } else 
    if (routerGetBuilderType() == "example_ListViewV2TabsPage") {
      ListViewV2TabsPage()
    } else 
    if (routerGetBuilderType() == "example_ListViewV2SwipeActionPage") {
      ListViewV2SwipeActionPage()
    } else 
    if (routerGetBuilderType() == "example_ListViewV2StickyTopPage") {
      ListViewV2StickyTopPage()
    } else 
    if (routerGetBuilderType() == "example_ListViewV2StickyRLTopPage") {
      ListViewV2StickyRLTopPage()
    } else 
    if (routerGetBuilderType() == "example_ListViewV2StickLayoutPage") {
      ListViewV2StickLayoutPage()
    } else 
    if (routerGetBuilderType() == "example_ListViewV2SpringRatioPage") {
      ListViewV2SpringRatioPage()
    } else 
    if (routerGetBuilderType() == "example_ListViewV2SlideDeletePage") {
      ListViewV2SlideDeletePage()
    } else 
    if (routerGetBuilderType() == "example_ListViewV2RefreshPage") {
      ListViewV2RefreshPage()
    } else 
    if (routerGetBuilderType() == "example_ListViewV2RefreshHeaderFooterPage") {
      ListViewV2RefreshHeaderFooterPage()
    } else 
    if (routerGetBuilderType() == "example_ListViewV2PositioningPage") {
      ListViewV2PositioningPage()
    } else 
    if (routerGetBuilderType() == "example_ListViewV2Page") {
      ListViewV2Page()
    } else 
    if (routerGetBuilderType() == "example_ListViewV2NoSpringPage") {
      ListViewV2NoSpringPage()
    } else 
    if (routerGetBuilderType() == "example_ListViewV2NoReboundPage") {
      ListViewV2NoReboundPage()
    } else 
    if (routerGetBuilderType() == "example_ListViewV2NoDataPage") {
      ListViewV2NoDataPage()
    } else 
    if (routerGetBuilderType() == "example_ListViewV2MaxSpringPage") {
      ListViewV2MaxSpringPage()
    } else 
    if (routerGetBuilderType() == "example_ListViewV2LoadMorePage") {
      ListViewV2LoadMorePage()
    } else 
    if (routerGetBuilderType() == "example_ListViewV2LazyPage") {
      ListViewV2LazyPage()
    } else 
    if (routerGetBuilderType() == "example_ListViewV2LazyDataOperationPage") {
      ListViewV2LazyDataOperationPage()
    } else 
    if (routerGetBuilderType() == "example_ListViewV2ItemGroupPage") {
      ListViewV2ItemGroupPage()
    } else 
    if (routerGetBuilderType() == "example_ListViewV2ItemGroupNoStickyPage") {
      ListViewV2ItemGroupNoStickyPage()
    } else 
    if (routerGetBuilderType() == "example_ListViewV2ItemGroupIndexPage") {
      ListViewV2ItemGroupIndexPage()
    } else 
    if (routerGetBuilderType() == "example_ListViewV2HeaderPage") {
      ListViewV2HeaderPage()
    } else 
    if (routerGetBuilderType() == "example_ListViewV2HeaderAndFooterPage") {
      ListViewV2HeaderAndFooterPage()
    } else 
    if (routerGetBuilderType() == "example_ListViewV2FooterPage") {
      ListViewV2FooterPage()
    } else 
    if (routerGetBuilderType() == "example_ListViewV2FixedBottomLoadPage") {
      ListViewV2FixedBottomLoadPage()
    } else 
    if (routerGetBuilderType() == "example_ListViewV2ErrorOrEmptyPage") {
      ListViewV2ErrorOrEmptyPage()
    } else 
    if (routerGetBuilderType() == "example_ListViewV2EnableSpringPage") {
      ListViewV2EnableSpringPage()
    } else 
    if (routerGetBuilderType() == "example_ListViewV2DataOperationPage") {
      ListViewV2DataOperationPage()
    } else 
    if (routerGetBuilderType() == "example_ListViewV2AutoRefreshPage") {
      ListViewV2AutoRefreshPage()
    } else 
    if (routerGetBuilderType() == "example_ListViewV2AutoLoadMorePage") {
      ListViewV2AutoLoadMorePage()
    } else 
    if (routerGetBuilderType() == "example_ListViewV2ArbitrarilyStickyTopPage") {
      ListViewV2ArbitrarilyStickyTopPage()
    } else 
    if (routerGetBuilderType() == "example_ListViewV2AdaptivePage2") {
      ListViewV2AdaptivePage2()
    } else 
    if (routerGetBuilderType() == "example_ListViewV2AdaptivePage") {
      ListViewV2AdaptivePage()
    } else 
    if (routerGetBuilderType() == "example_ListLayoutV2UpAndDownPage") {
      ListLayoutV2UpAndDownPage()
    } else 
    if (routerGetBuilderType() == "example_ListLayoutV2TabsPage") {
      ListLayoutV2TabsPage()
    } else 
    if (routerGetBuilderType() == "example_ListLayoutV2SwipeActionPage") {
      ListLayoutV2SwipeActionPage()
    } else 
    if (routerGetBuilderType() == "example_ListLayoutV2StickyTopRefreshPage") {
      ListLayoutV2StickyTopRefreshPage()
    } else 
    if (routerGetBuilderType() == "example_ListLayoutV2StickyTopPage") {
      ListLayoutV2StickyTopPage()
    } else 
    if (routerGetBuilderType() == "example_ListLayoutV2StickPage") {
      ListLayoutV2StickPage()
    } else 
    if (routerGetBuilderType() == "example_ListLayoutV2SpringRatioPage") {
      ListLayoutV2SpringRatioPage()
    } else 
    if (routerGetBuilderType() == "example_ListLayoutV2SlideDeletePage") {
      ListLayoutV2SlideDeletePage()
    } else 
    if (routerGetBuilderType() == "example_ListLayoutV2RefreshPage") {
      ListLayoutV2RefreshPage()
    } else 
    if (routerGetBuilderType() == "example_ListLayoutV2RefreshHeaderFooterPage") {
      ListLayoutV2RefreshHeaderFooterPage()
    } else 
    if (routerGetBuilderType() == "example_ListLayoutV2PositioningPage") {
      ListLayoutV2PositioningPage()
    } else 
    if (routerGetBuilderType() == "example_ListLayoutV2Page") {
      ListLayoutV2Page()
    } else 
    if (routerGetBuilderType() == "example_ListLayoutV2NoSpringPage") {
      ListLayoutV2NoSpringPage()
    } else 
    if (routerGetBuilderType() == "example_ListLayoutV2NoReboundPage") {
      ListLayoutV2NoReboundPage()
    } else 
    if (routerGetBuilderType() == "example_ListLayoutV2MaxSpringPage") {
      ListLayoutV2MaxSpringPage()
    } else 
    if (routerGetBuilderType() == "example_ListLayoutV2LoadMorePage") {
      ListLayoutV2LoadMorePage()
    } else 
    if (routerGetBuilderType() == "example_ListLayoutV2LazyUpAndDownPage") {
      ListLayoutV2LazyUpAndDownPage()
    } else 
    if (routerGetBuilderType() == "example_ListLayoutV2LazyPage") {
      ListLayoutV2LazyPage()
    } else 
    if (routerGetBuilderType() == "example_ListLayoutV2LazyDataOperationPage") {
      ListLayoutV2LazyDataOperationPage()
    } else 
    if (routerGetBuilderType() == "example_ListLayoutV2ItemGroupPage") {
      ListLayoutV2ItemGroupPage()
    } else 
    if (routerGetBuilderType() == "example_ListLayoutV2ItemGroupNoStickyPage") {
      ListLayoutV2ItemGroupNoStickyPage()
    } else 
    if (routerGetBuilderType() == "example_ListLayoutV2ItemGroupIndexPage") {
      ListLayoutV2ItemGroupIndexPage()
    } else 
    if (routerGetBuilderType() == "example_ListLayoutV2HeaderPage") {
      ListLayoutV2HeaderPage()
    } else 
    if (routerGetBuilderType() == "example_ListLayoutV2HeaderAndFooterPage") {
      ListLayoutV2HeaderAndFooterPage()
    } else 
    if (routerGetBuilderType() == "example_ListLayoutV2FooterPage") {
      ListLayoutV2FooterPage()
    } else 
    if (routerGetBuilderType() == "example_ListLayoutV2FixedFooterPage") {
      ListLayoutV2FixedFooterPage()
    } else 
    if (routerGetBuilderType() == "example_ListLayoutV2FixedBottomLoadPage") {
      ListLayoutV2FixedBottomLoadPage()
    } else 
    if (routerGetBuilderType() == "example_ListLayoutV2ErrorOrEmptyPage") {
      ListLayoutV2ErrorOrEmptyPage()
    } else 
    if (routerGetBuilderType() == "example_ListLayoutV2EnableSpringPage") {
      ListLayoutV2EnableSpringPage()
    } else 
    if (routerGetBuilderType() == "example_ListLayoutV2DataOperationPage") {
      ListLayoutV2DataOperationPage()
    } else 
    if (routerGetBuilderType() == "example_ListLayoutV2AutoRefreshPage") {
      ListLayoutV2AutoRefreshPage()
    } else 
    if (routerGetBuilderType() == "example_ListLayoutV2AutoLoadMorePage") {
      ListLayoutV2AutoLoadMorePage()
    } else 
    if (routerGetBuilderType() == "example_ListLayoutV2ArbitrarilyStickyTopPage") {
      ListLayoutV2ArbitrarilyStickyTopPage()
    } else 
    if (routerGetBuilderType() == "example_ListLayoutV2AdaptivePage2") {
      ListLayoutV2AdaptivePage2()
    } else 
    if (routerGetBuilderType() == "example_ListLayoutV2AdaptivePage") {
      ListLayoutV2AdaptivePage()
    } else 
    if (routerGetBuilderType() == "example_GridViewV2TabsPage") {
      GridViewV2TabsPage()
    } else 
    if (routerGetBuilderType() == "example_GridViewV2StickyTopPage") {
      GridViewV2StickyTopPage()
    } else 
    if (routerGetBuilderType() == "example_GridViewV2StickyRLTopPage") {
      GridViewV2StickyRLTopPage()
    } else 
    if (routerGetBuilderType() == "example_GridViewV2StickLayoutViewPage") {
      GridViewV2StickLayoutViewPage()
    } else 
    if (routerGetBuilderType() == "example_GridViewV2SpringRatioPage") {
      GridViewV2SpringRatioPage()
    } else 
    if (routerGetBuilderType() == "example_GridViewV2RefreshPage") {
      GridViewV2RefreshPage()
    } else 
    if (routerGetBuilderType() == "example_GridViewV2RefreshHeaderFooterPage") {
      GridViewV2RefreshHeaderFooterPage()
    } else 
    if (routerGetBuilderType() == "example_GridViewV2RefreshAndLoadPage") {
      GridViewV2RefreshAndLoadPage()
    } else 
    if (routerGetBuilderType() == "example_GridViewV2PositioningPage") {
      GridViewV2PositioningPage()
    } else 
    if (routerGetBuilderType() == "example_GridViewV2Page") {
      GridViewV2Page()
    } else 
    if (routerGetBuilderType() == "example_GridViewV2NoSpringPage") {
      GridViewV2NoSpringPage()
    } else 
    if (routerGetBuilderType() == "example_GridViewV2NoReboundPage") {
      GridViewV2NoReboundPage()
    } else 
    if (routerGetBuilderType() == "example_GridViewV2NoDataPage") {
      GridViewV2NoDataPage()
    } else 
    if (routerGetBuilderType() == "example_GridViewV2MaxSpringPage") {
      GridViewV2MaxSpringPage()
    } else 
    if (routerGetBuilderType() == "example_GridViewV2LoadMorePage") {
      GridViewV2LoadMorePage()
    } else 
    if (routerGetBuilderType() == "example_GridViewV2LazyRefreshAndLoadPage") {
      GridViewV2LazyRefreshAndLoadPage()
    } else 
    if (routerGetBuilderType() == "example_GridViewV2LazyPage") {
      GridViewV2LazyPage()
    } else 
    if (routerGetBuilderType() == "example_GridViewV2HeaderPage") {
      GridViewV2HeaderPage()
    } else 
    if (routerGetBuilderType() == "example_GridViewV2HeaderAndFooterPage") {
      GridViewV2HeaderAndFooterPage()
    } else 
    if (routerGetBuilderType() == "example_GridViewV2FooterPage") {
      GridViewV2FooterPage()
    } else 
    if (routerGetBuilderType() == "example_GridViewV2FixedBottomLoadPage") {
      GridViewV2FixedBottomLoadPage()
    } else 
    if (routerGetBuilderType() == "example_GridViewV2EnableSpringPage") {
      GridViewV2EnableSpringPage()
    } else 
    if (routerGetBuilderType() == "example_GridViewV2AutoRefreshPage") {
      GridViewV2AutoRefreshPage()
    } else 
    if (routerGetBuilderType() == "example_GridViewV2AutoLoadMorePage") {
      GridViewV2AutoLoadMorePage()
    } else 
    if (routerGetBuilderType() == "example_GridViewV2ArbitrarilyStickyTopPage") {
      GridViewV2ArbitrarilyStickyTopPage()
    } else 
    if (routerGetBuilderType() == "example_GridViewV2AdaptiveTopPage") {
      GridViewV2AdaptiveTopPage()
    } else 
    if (routerGetBuilderType() == "example_GridViewV2AdaptiveBottomPage") {
      GridViewV2AdaptiveBottomPage()
    } else 
    if (routerGetBuilderType() == "example_GridV2DropPage") {
      GridV2DropPage()
    } else 
    if (routerGetBuilderType() == "example_GridLayoutV2TabsPage") {
      GridLayoutV2TabsPage()
    } else 
    if (routerGetBuilderType() == "example_GridLayoutV2StickyTopPage") {
      GridLayoutV2StickyTopPage()
    } else 
    if (routerGetBuilderType() == "example_GridLayoutV2StickyRLTopPage") {
      GridLayoutV2StickyRLTopPage()
    } else 
    if (routerGetBuilderType() == "example_GridLayoutV2StickLayoutViewPage") {
      GridLayoutV2StickLayoutViewPage()
    } else 
    if (routerGetBuilderType() == "example_GridLayoutV2SpringRatioPage") {
      GridLayoutV2SpringRatioPage()
    } else 
    if (routerGetBuilderType() == "example_GridLayoutV2RefreshPage") {
      GridLayoutV2RefreshPage()
    } else 
    if (routerGetBuilderType() == "example_GridLayoutV2RefreshHeaderFooterPage") {
      GridLayoutV2RefreshHeaderFooterPage()
    } else 
    if (routerGetBuilderType() == "example_GridLayoutV2RefreshAndLoadPage") {
      GridLayoutV2RefreshAndLoadPage()
    } else 
    if (routerGetBuilderType() == "example_GridLayoutV2PositioningPage") {
      GridLayoutV2PositioningPage()
    } else 
    if (routerGetBuilderType() == "example_GridLayoutV2Page") {
      GridLayoutV2Page()
    } else 
    if (routerGetBuilderType() == "example_GridLayoutV2NoSpringPage") {
      GridLayoutV2NoSpringPage()
    } else 
    if (routerGetBuilderType() == "example_GridLayoutV2NoReboundPage") {
      GridLayoutV2NoReboundPage()
    } else 
    if (routerGetBuilderType() == "example_GridLayoutV2NoDataPage") {
      GridLayoutV2NoDataPage()
    } else 
    if (routerGetBuilderType() == "example_GridLayoutV2MaxSpringPage") {
      GridLayoutV2MaxSpringPage()
    } else 
    if (routerGetBuilderType() == "example_GridLayoutV2LoadMorePage") {
      GridLayoutV2LoadMorePage()
    } else 
    if (routerGetBuilderType() == "example_GridLayoutV2LazyRefreshAndLoadPage") {
      GridLayoutV2LazyRefreshAndLoadPage()
    } else 
    if (routerGetBuilderType() == "example_GridLayoutV2LazyPage") {
      GridLayoutV2LazyPage()
    } else 
    if (routerGetBuilderType() == "example_GridLayoutV2HeaderPage") {
      GridLayoutV2HeaderPage()
    } else 
    if (routerGetBuilderType() == "example_GridLayoutV2HeaderAndFooterPage") {
      GridLayoutV2HeaderAndFooterPage()
    } else 
    if (routerGetBuilderType() == "example_GridLayoutV2FooterPage") {
      GridLayoutV2FooterPage()
    } else 
    if (routerGetBuilderType() == "example_GridLayoutV2FixedBottomLoadPage") {
      GridLayoutV2FixedBottomLoadPage()
    } else 
    if (routerGetBuilderType() == "example_GridLayoutV2EnableSpringPage") {
      GridLayoutV2EnableSpringPage()
    } else 
    if (routerGetBuilderType() == "example_GridLayoutV2AutoRefreshPage") {
      GridLayoutV2AutoRefreshPage()
    } else 
    if (routerGetBuilderType() == "example_GridLayoutV2AutoLoadMorePage") {
      GridLayoutV2AutoLoadMorePage()
    } else 
    if (routerGetBuilderType() == "example_GridLayoutV2ArbitrarilyStickyTopPage") {
      GridLayoutV2ArbitrarilyStickyTopPage()
    } else 
    if (routerGetBuilderType() == "example_GridLayoutV2AdaptiveTopPage") {
      GridLayoutV2AdaptiveTopPage()
    } else 
    if (routerGetBuilderType() == "example_GridLayoutV2AdaptiveBottomPage") {
      GridLayoutV2AdaptiveBottomPage()
    } else 
    if (routerGetBuilderType() == "example_FlowViewV2TopActionBarPage") {
      FlowViewV2TopActionBarPage()
    } else 
    if (routerGetBuilderType() == "example_FlowViewV2TabsPage") {
      FlowViewV2TabsPage()
    } else 
    if (routerGetBuilderType() == "example_FlowViewV2StickyTopPage") {
      FlowViewV2StickyTopPage()
    } else 
    if (routerGetBuilderType() == "example_FlowViewV2StickyTopActionBarPage") {
      FlowViewV2StickyTopActionBarPage()
    } else 
    if (routerGetBuilderType() == "example_FlowViewV2StickyRLTopPage") {
      FlowViewV2StickyRLTopPage()
    } else 
    if (routerGetBuilderType() == "example_FlowViewV2SpringRatioPage") {
      FlowViewV2SpringRatioPage()
    } else 
    if (routerGetBuilderType() == "example_FlowViewV2RefreshPage") {
      FlowViewV2RefreshPage()
    } else 
    if (routerGetBuilderType() == "example_FlowViewV2RefreshHeaderAndFooterPage") {
      FlowViewV2RefreshHeaderAndFooterPage()
    } else 
    if (routerGetBuilderType() == "example_FlowViewV2RefreshAndLoadMorePage") {
      FlowViewV2RefreshAndLoadMorePage()
    } else 
    if (routerGetBuilderType() == "example_FlowViewV2PositioningPage") {
      FlowViewV2PositioningPage()
    } else 
    if (routerGetBuilderType() == "example_FlowViewV2Page") {
      FlowViewV2Page()
    } else 
    if (routerGetBuilderType() == "example_FlowViewV2NoSpringPage") {
      FlowViewV2NoSpringPage()
    } else 
    if (routerGetBuilderType() == "example_FlowViewV2NoReboundPage") {
      FlowViewV2NoReboundPage()
    } else 
    if (routerGetBuilderType() == "example_FlowViewV2NoDataPage") {
      FlowViewV2NoDataPage()
    } else 
    if (routerGetBuilderType() == "example_FlowViewV2MaxSpringPage") {
      FlowViewV2MaxSpringPage()
    } else 
    if (routerGetBuilderType() == "example_FlowViewV2LoadMorePage") {
      FlowViewV2LoadMorePage()
    } else 
    if (routerGetBuilderType() == "example_FlowViewV2LazyRefreshAndLoadMorePage") {
      FlowViewV2LazyRefreshAndLoadMorePage()
    } else 
    if (routerGetBuilderType() == "example_FlowViewV2LazyPage") {
      FlowViewV2LazyPage()
    } else 
    if (routerGetBuilderType() == "example_FlowViewV2HeaderPage") {
      FlowViewV2HeaderPage()
    } else 
    if (routerGetBuilderType() == "example_FlowViewV2HeaderAndFooterPage") {
      FlowViewV2HeaderAndFooterPage()
    } else 
    if (routerGetBuilderType() == "example_FlowViewV2FooterPage") {
      FlowViewV2FooterPage()
    } else 
    if (routerGetBuilderType() == "example_FlowViewV2FixedBottomPage") {
      FlowViewV2FixedBottomPage()
    } else 
    if (routerGetBuilderType() == "example_FlowViewV2EnableSpringPage") {
      FlowViewV2EnableSpringPage()
    } else 
    if (routerGetBuilderType() == "example_FlowViewV2AutoRefreshPage") {
      FlowViewV2AutoRefreshPage()
    } else 
    if (routerGetBuilderType() == "example_FlowViewV2AutoLoadMorePage") {
      FlowViewV2AutoLoadMorePage()
    } else 
    if (routerGetBuilderType() == "example_FlowViewV2ArbitrarilyStickyTopPage") {
      FlowViewV2ArbitrarilyStickyTopPage()
    } else 
    if (routerGetBuilderType() == "example_FlowViewV2AdaptiveTopPage") {
      FlowViewV2AdaptiveTopPage()
    } else 
    if (routerGetBuilderType() == "example_FlowViewV2AdaptiveBottomPage") {
      FlowViewV2AdaptiveBottomPage()
    } else 
    if (routerGetBuilderType() == "example_FlowLayoutV2TopActionBarPage") {
      FlowLayoutV2TopActionBarPage()
    } else 
    if (routerGetBuilderType() == "example_FlowLayoutV2TabsPage") {
      FlowLayoutV2TabsPage()
    } else 
    if (routerGetBuilderType() == "example_FlowLayoutV2StickyTopPage") {
      FlowLayoutV2StickyTopPage()
    } else 
    if (routerGetBuilderType() == "example_FlowLayoutV2StickyRLTopPage") {
      FlowLayoutV2StickyRLTopPage()
    } else 
    if (routerGetBuilderType() == "example_FlowLayoutV2SpringRatioPage") {
      FlowLayoutV2SpringRatioPage()
    } else 
    if (routerGetBuilderType() == "example_FlowLayoutV2RefreshPage") {
      FlowLayoutV2RefreshPage()
    } else 
    if (routerGetBuilderType() == "example_FlowLayoutV2RefreshHeaderAndFooterPage") {
      FlowLayoutV2RefreshHeaderAndFooterPage()
    } else 
    if (routerGetBuilderType() == "example_FlowLayoutV2RefreshAndLoadMorePage") {
      FlowLayoutV2RefreshAndLoadMorePage()
    } else 
    if (routerGetBuilderType() == "example_FlowLayoutV2PositioningPage") {
      FlowLayoutV2PositioningPage()
    } else 
    if (routerGetBuilderType() == "example_FlowLayoutV2Page") {
      FlowLayoutV2Page()
    } else 
    if (routerGetBuilderType() == "example_FlowLayoutV2NoSpringPage") {
      FlowLayoutV2NoSpringPage()
    } else 
    if (routerGetBuilderType() == "example_FlowLayoutV2NoReboundPage") {
      FlowLayoutV2NoReboundPage()
    } else 
    if (routerGetBuilderType() == "example_FlowLayoutV2NoDataPage") {
      FlowLayoutV2NoDataPage()
    } else 
    if (routerGetBuilderType() == "example_FlowLayoutV2MaxSpringPage") {
      FlowLayoutV2MaxSpringPage()
    } else 
    if (routerGetBuilderType() == "example_FlowLayoutV2LoadMorePage") {
      FlowLayoutV2LoadMorePage()
    } else 
    if (routerGetBuilderType() == "example_FlowLayoutV2LazyRefreshAndLoadMorePage") {
      FlowLayoutV2LazyRefreshAndLoadMorePage()
    } else 
    if (routerGetBuilderType() == "example_FlowLayoutV2LazyPage") {
      FlowLayoutV2LazyPage()
    } else 
    if (routerGetBuilderType() == "example_FlowLayoutV2HeaderPage") {
      FlowLayoutV2HeaderPage()
    } else 
    if (routerGetBuilderType() == "example_FlowLayoutV2HeaderAndFooterPage") {
      FlowLayoutV2HeaderAndFooterPage()
    } else 
    if (routerGetBuilderType() == "example_FlowLayoutV2FooterPage") {
      FlowLayoutV2FooterPage()
    } else 
    if (routerGetBuilderType() == "example_FlowLayoutV2FixedBottomPage") {
      FlowLayoutV2FixedBottomPage()
    } else 
    if (routerGetBuilderType() == "example_FlowLayoutV2EnableSpringPage") {
      FlowLayoutV2EnableSpringPage()
    } else 
    if (routerGetBuilderType() == "example_FlowLayoutV2AutoRefreshPage") {
      FlowLayoutV2AutoRefreshPage()
    } else 
    if (routerGetBuilderType() == "example_FlowLayoutV2AutoLoadMorePage") {
      FlowLayoutV2AutoLoadMorePage()
    } else 
    if (routerGetBuilderType() == "example_FlowLayoutV2AdaptiveTopPage") {
      FlowLayoutV2AdaptiveTopPage()
    } else 
    if (routerGetBuilderType() == "example_FlowLayoutV2AdaptiveBottomPage") {
      FlowLayoutV2AdaptiveBottomPage()
    } else 
    if (routerGetBuilderType() == "example_V2SecondFloorExample2") {
      V2SecondFloorExample2()
    } else 
    if (routerGetBuilderType() == "example_V2SecondFloorExample") {
      V2SecondFloorExample()
    } else 
    if (routerGetBuilderType() == "example_SecondFloorPageV2") {
      SecondFloorPageV2()
    } 

  }

}


/**
 * AUTHOR:AbnerMing
 * DATE:2026年5月28日 15时31分0秒
 * INTRODUCE:路由配置,此路由配置文件为自动生成，无特殊情况下请无须改动
 * */
export class ExampleRouterConfig implements RouterConfig {
  getModuleName(): string {
    return "example"
  }

  async initRouter(builderName: string): Promise<void> {
    return await new Promise((resolve: Function) => {
      importPath(builderName)
      routerInitBuilder(builderName, wrapBuilder(viewBuilder))
      resolve()
    })
  }
}